name: deployment 

on:
 push:
  branches:
    - main

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
   - name: checkout
     uses: actions/checkout@v4
  
   - name: Setup Node
     uses: actions/setup-node@v4
     with:
       node-version: 20

   - name: install depen
     run: npm install

   - name: build
     run: npm run build

   - name: Copy build files to Azure VM
     uses: appleboy/scp-action@v0.1.7
     with:
      host: ${{ secrets.AZURE_VM_HOST }}
      username: ${{ secrets.AZURE_VM_USER }}
      key: ${{ secrets.AZURE_VM_SSH_KEY }}
      source: "build/*"
      target: "/var/www/html"
      strip_components: 1
